### ISSUE TITLE
Ionic 2 rc3 error "Can't bind to 'options'"

### ISSUE THREAD

**Issue by theromis** [jkuri/ng2-uploader#151]
Everything worked fine, after update gives this error.
```
Can't bind to 'options' since it isn't a known property of 'div'. ("
                <ion-item>
                    <div ngFileDrop
                         [ERROR ->][options]="profileOptions"
```
template.html
```html
                        <div ngFileDrop
                             [ngClass]="{'file-over': protectionDropZoneOver}"
                             [options]="protectionOptions"
                             (onUpload)="handleUpload($event)"
                             (onFileOver)="fileOverBaseProtection($event)"
                             class="image-drop-zone">
```

`app.module.ts`
```typescript
import { Ng2UploaderModule } from 'ng2-uploader';
...
@NgModule({
  imports: [
    IonicModule.forRoot(MyApp),
    Ng2UploaderModule,
    BrowserModule,
    FormsModule,
    MomentModule,
    AngularFireModule.initializeApp(firebaseConfig, myFirebaseAuthConfig),
  ],
....
```

**Comment by theromis** [comment]
Just found in closed issues similar
https://github.com/jkuri/ng2-uploader/issues/146
trying what been done there, doesn't help.

**Comment by theromis** [comment]
ok my problem was in `ng2-upload` version
I've used 1.5.7 (1.6.0 not works as well), downgrade to 1.5.5 fixed issue (1.5.6) still doing the "stuff".
problem in 1.5.5 that I have to run `build --dev` which is wrong.

Please help me with update to the latest version, I really love this module.
`package.json`
```
{
  "name": "ionic-chat-lonje",
  "author": "Lonje",
  "homepage": "https://chat.lonje.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/jasmine": "^2.5.38",
    "@types/socket.io-client": "1.4.27",
    "angular2-jwt": "0.1.23",
    "angular2-moment": "^1.0.0-beta.rc.1",
    "angularfire2": "^2.0.0-beta.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "ng2-tag-input": "^0.4.4",
    "ng2-uploader": "1.5.5",
    "rxjs": "5.0.0-beta.12",
    "socket.io-client": "1.5.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "@types/node": "0.0.2",
    "typescript": "2.0.6"
  },
  "cordovaPlugins": [
    "cordova-plugin-crosswalk-webview",
    "cordova-plugin-googleplus",
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ]
}
```

**Comment by theromis** [comment]
@jkuri hey, I know you the man, please help to fix the stuff.

**Comment by jkuri** [comment]
okay :) I'll check it out now

**Comment by jkuri** [comment]
@theromis can you check `1.6.1` and let me know please?

**Comment by theromis** [comment]
still the same
```javascript
polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'div'. ("
                <ion-item>
                    <div ngFileDrop
                         [ERROR ->][options]="profileOptions"
                         (onUpload)="handleUpload($event)"
               "): ProfilePage@165:25
```

**Comment by jkuri** [comment]
[ng2-uploader.com.zip](https://github.com/jkuri/ng2-uploader/files/642804/ng2-uploader.com.zip)

here's the demo page, please check how its done here. 
to run this: `npm install && npm run serve`

**Comment by theromis** [comment]
just unpacked it and ran
`npm install`
`npm run serve`

and got same error
```
vendor.js:7698 Unhandled Promise rejection: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'div'. ("
               *ngIf="!response"
               ngFileDrop
               [ERROR ->][options]="options"
               (onUpload)="handleUpload($event)"
               [ngClass]="{'file"): AppDemoComponent@8:15
Can't bind to 'options' since it isn't a known property of 'input'. ("
                     class="hidden" 
                     ngFileSelect
                     [ERROR ->][options]="options" 
                     (onUpload)="handleUpload($event)">
              Browse
"): AppDemoComponent@18:21 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'div'. ("
               *ngIf="!response"
               ngFileDrop
               [ERROR ->][options]="options"
               (onUpload)="handleUpload($event)"
               [ngClass]="{'file"): AppDemoComponent@8:15
Can't bind to 'options' since it isn't a known property of 'input'. ("
                     class="hidden" 
                     ngFileSelect
                     [ERROR ->][options]="options" 
                     (onUpload)="handleUpload($event)">
              Browse
"): AppDemoComponent@18:21
    at TemplateParser.parse (http://localhost:4200/vendor.js:34730:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/vendor.js:44520:51)
    at http://localhost:4200/vendor.js:44440:62
    at Set.forEach (native)
    at RuntimeCompiler._compileComponents (http://localhost:4200/vendor.js:44440:19)
    at createResult (http://localhost:4200/vendor.js:44336:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.js:7542:26)
    at Zone.run (http://localhost:4200/vendor.js:7424:43)
    at http://localhost:4200/vendor.js:7812:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.js:7575:35)consoleError @ vendor.js:7698
vendor.js:7700 Error: Uncaught (in promise): Error: Template parse errors:(…)
```

**Comment by jkuri** [comment]
Please fix you typescript version to exact `2.0.10`

**Comment by theromis** [comment]
```
head /Users/vasilro/Downloads/ng2-uploader.com/node_modules/typescript/package.json
{
  "_args": [
    [
      {
        "raw": "typescript@^2.0.10",
        "scope": null,
        "escapedName": "typescript",
        "name": "typescript",
        "rawSpec": "^2.0.10",
        "spec": ">=2.0.10 <3.0.0",
```

**Comment by jkuri** [comment]
you need to set it without starting `^`, so:
```js
"typescript": "2.0.10"
```

**Comment by theromis** [comment]
this is exactly what I did, and reinstalling script right now

**Comment by theromis** [comment]
it works, thank you
will try on my project now

**Comment by jkuri** [comment]
no problem, was having exact issue with typescript version whole day in work :(

**Comment by theromis** [comment]
but setting this on my project still giving same error
```
{
  "name": "ionic-chat-lonje",
  "author": "Lonje",
  "homepage": "https://chat.lonje.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build --dev",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/jasmine": "^2.5.38",
    "@types/socket.io-client": "1.4.27",
    "angular2-jwt": "0.1.23",
    "angular2-moment": "^1.0.0-beta.rc.1",
    "angularfire2": "^2.0.0-beta.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "ng2-tag-input": "^0.4.4",
    "ng2-uploader": "1.6.1",
    "rxjs": "5.0.0-beta.12",
    "socket.io-client": "1.5.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "@types/node": "0.0.2",
    "typescript": "2.0.10"
  },
  "cordovaPlugins": [
    "cordova-plugin-crosswalk-webview",
    "cordova-plugin-googleplus",
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ]
}
```

**Comment by jkuri** [comment]
what happens if you upgrade angular versions to 2.2.1?

**Comment by theromis** [comment]
```
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/common@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/compiler@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/compiler-cli@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/core@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/forms@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/http@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/platform-browser@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/platform-browser-dynamic@2.1.1 but none was installed.
npm WARN ionic-angular@2.0.0-rc.3 requires a peer of @angular/platform-server@2.1.1 but none was installed.
```

**Comment by jkuri** [comment]
sorry but unfamiliar with ionic-angular though.

**Comment by theromis** [comment]
upcoming rc4 will switch to 2.2.1, unfortunately rc3 hardly dependant from 2.1.1

**Comment by theromis** [comment]
well, will wait for rc4, and sit on 1.5.5 until, this should happened next week

**Comment by jkuri** [comment]
okay, basically you are not missing much, I just added AoT compiler.

**Comment by theromis** [comment]
thanks, will write here about my upgrade attempts later

**Comment by kolkov** [comment]
Me too ((
![image](https://cloud.githubusercontent.com/assets/3740898/21062974/5b8352aa-be64-11e6-89e5-27e03084b778.png)

**Comment by alan345** [comment]
Hello, Same issue here. What should we do ? 
I have 
"typescript": "2.0.10",
and 
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",

Thanks for your help

**Comment by alan345** [comment]
I have updated angular 
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",

but still the same issue with option

Thanks for your help !!
<img width="554" alt="screen shot 2016-12-09 at 4 58 18 pm" src="https://cloud.githubusercontent.com/assets/15246526/21069639/c937b1b2-be30-11e6-96c7-ed7e440d932b.png">

**Comment by scurk15** [comment]
I have the same problem since i updated to 1.6.1, but 1.5.3 worked fine.

**Comment by ventr1x** [comment]
You just gotta love this node/js ecosystem.
It is clearly an issue with the current version of the plugin, I personally don't have the time to go through the source myself.

You posted a systemjs example in #146 and the only difference from my project is the version of ng2-uploader (1.5.5 instead of latest). 1.5. indeed seems to work, at least concerning this error.

**Comment by vladisOV** [comment]
+1 same error

**Comment by theromis** [comment]
@jkuri finally updated to angular 2.2.1 but getting same issues
here is how my `package.json`
```json
{
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build --dev",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/jasmine": "^2.5.38",
    "@types/socket.io-client": "1.4.27",
    "angular2-jwt": "^0.1.26",
    "angular2-moment": "^1.0.0-beta.rc.1",
    "angularfire2": "^2.0.0-beta.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionic-ratings": "^0.3.0",
    "ionicons": "3.0.0",
    "ng2-tag-input": "^0.4.4",
    "ng2-uploader": "1.6.1",
    "rxjs": "5.0.0-beta.12",
    "socket.io-client": "1.5.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "@types/node": "0.0.2",
    "typescript": "2.0.10"
  },
  "cordovaPlugins": [
    "cordova-plugin-crosswalk-webview",
    "cordova-plugin-googleplus",
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-apprate"
  ]
}
```

**Comment by gnovotny** [comment]
the pull request by parag-patwardhan works for me

**Comment by theromis** [comment]
@jkuri Could you merge https://github.com/jkuri/ng2-uploader/pull/154 ?

**Comment by jkuri** [comment]
done.
